version: '3'

services:
  backend:
    restart: always
    build: ../Game-Interface-Flows-Backend/
    ports:
      - "8000:8000"
    container_name: backend
    volumes:
      - static_volume:/app/static
  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/home/evlko/Projects/game-interface-flows/Game-Interface-Flows-Backend/static
      - ./nginx.conf:/etc/nginx/nginx.conf
volumes:
  static_volume: