version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - djangonetwork
  ml:
    restart: always
    build: ../Game-Interface-Flows-ML/
    command: >
      sh -c "uvicorn api.app:app --reload --host 0.0.0.0 --port 8001 --log-level critical"
    ports:
      - "8001:8001"
    container_name: ml
    networks:
      - djangonetwork
  api:
    restart: always
    env_file:
      - .env
    build: ../Game-Interface-Flows-Backend/
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py createsuperuser --noinput --username $DJANGO_SUPERUSER_USERNAME
             python3 manage.py runserver 0.0.0.0:8000
             "
    ports:
      - "8000:8000"
    container_name: api
    depends_on:
      - db
      - ml
    links:
      - db:db
      - ml:ml
    networks:
      - djangonetwork
  client:
    restart: always
    build: ../Game-Interface-Flows-Frontend/
    ports:
      - "3000:3000"
    container_name: client
    depends_on:
      - api
    links:
      - api:api
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge

volumes:
  db: